### ISSUE TITLE
Argument completer does not work well with veggies with blanks

### ISSUE THREAD

**Issue by andreasjordan** [jdhitsolutions/PSTeachingTools#10]
The argument completer does not put quotes around those veggies that have a blank in the name like "russet potato".
Don't know the solution right now but will try to research...

**Comment by andreasjordan** [comment]
Maybe use this: https://issueexplorer.com/issue/PowerShell/SecretManagement/91
`$completionText = if ($_ -match '\s') { "'$_'" } else { $_ }`

**Comment by jdhitsolutions** [comment]
I've come across this in my other projects. Your solution is on the right track. Thanks for bringing up this issue.

**Comment by jdhitsolutions** [comment]
This should be fixed in v4.1.0 if you want to update the module and try again.

**Comment by andreasjordan** [comment]
Yes! Thanks a lot for the quick fix.
