### ISSUE TITLE
Cannot change the CookedState back to Raw

### ISSUE THREAD

**Issue by andreasjordan** [jdhitsolutions/PSTeachingTools#11]
I can change the CookedState from Raw to something else, but not back to Raw.

I'm too blind to see where in the code this is tested - can you help me?

![image](https://user-images.githubusercontent.com/66946165/148806375-b1abd48d-93ef-4381-9798-a687cf939f92.png)

**Comment by andreasjordan** [comment]
Found the problem:

![image](https://user-images.githubusercontent.com/66946165/148807481-cd4c85f6-d137-4120-a332-5013641e3849.png)

The test `if ($CookingState)` (line 111) does not use the string but the index of the enum - and that is 0 as it is the first one and so it is false. You should test for the $PSBoundParameters and see if the Parameter was used.

Not a problem but not nice: When piping to Set-Vegetable, $count is always set because of `[Parameter(ValueFromPipelineByPropertyName)]`. So the Count property is always set as you can see in the verbose output.

**Comment by andreasjordan** [comment]
Code for copy-paste:
```
Get-Vegetable -Name zucchini | Set-Vegetable -CookingState Grilled -Passthru
Get-Vegetable -Name zucchini | Set-Vegetable -CookingState Baked -Passthru -Verbose
Get-Vegetable -Name zucchini | Set-Vegetable -CookingState Raw -Passthru -Verbose

$CookingState = 'Raw'
if ($CookingState) { 'will work' } else { 'will not work' }

$CookingState = [PSTeachingTools.VegStatus]::Raw
if ($CookingState) { 'will work' } else { 'will not work' }
```

**Comment by jdhitsolutions** [comment]
This is one of the challenges when working with classes and enums in your own code. This wasn't an issue they way I was using the commands for beginning PowerShell classes but there is room for improvement.

**Comment by jdhitsolutions** [comment]
The other problem  I see is that I never finished setting up parameter sets. Working on cleaning this up.

**Comment by jdhitsolutions** [comment]
I think I have this sorted out. Update to v4.2.0 from the PowerShell Gallery and try again.

**Comment by andreasjordan** [comment]
Yes, it works.

Only drawback: Verbose is a bit noisey now:
![image](https://user-images.githubusercontent.com/66946165/148980364-4a1af2e5-ab59-4783-9930-0719f55b0ba7.png)

I think `$PSBoundParameters | Out-String | Write-Verbose` should be `$PSBoundParameters | Out-String | Write-Debug`.
