### ISSUE TITLE
Get-Vegetable has no output

### ISSUE THREAD

**Issue by Tickkid** [jdhitsolutions/PSTeachingTools#5]
Hello, I'm using Powershell 5.1.18362.752 and version 3.2.0 of psteachingtools.  I've installed the module, but when I run Get-Vegetable, nothing comes up at all.  I receive errors when trying to get help or run New-Vegetable - but I do get help working on get-vegetable.

**Comment by jdhitsolutions** [comment]
I'm assuming since you closed this you got it working after all.  This is the second issue on the vegetable commands so I want to make sure something isn't happening that I'm not taking into account.

**Comment by Tickkid** [comment]
It was a problem that I only had on the autolab machine. On my regular
desktop it was working fine so I assumed that it was an issue with my lab
and not the commands.

**Comment by jdhitsolutions** [comment]
That is curious. The module should install and run in any Windows 10 environment. I'm happy to look into this further if you can tell me the error messages you are seeing.

**Comment by Tickkid** [comment]
That would be great.  I'm not going to be back to my testing machine until
Monday, but I'll send you the help messages errors when can grab them.

**Comment by jdhitsolutions** [comment]
I pushed a new version of the module to the PowerShell Gallery with additional verbose messaging that might help pinpoint where things are going astray. Uninstall the PSTeachingTools module completely. Exit PowerShell and start a new session. Install v3.2.1 of the PSTeachingTools module. I want to make sure we are in a completely clean environment. Then import the module with verbose output and try `Get-Vegetable`.

```powershell
Import-Module PSTeachingtools -verbose
Get-Vegetable -verbose
```

If you get no results, post the output from these commands.

**Comment by Tickkid** [comment]
It is all working now, but I re-did everything from scratch, so perhaps I
messed up the first time I did it.  Thank you for your help.

**Comment by jdhitsolutions** [comment]
Ok then.
