### ISSUE TITLE
links are broken

### ISSUE THREAD

**Issue by ltdeta** [jdhitsolutions/PSTeachingTools#7]
The following links are broken

See the [about_psteachingtools ](https://github.com/jdhitsolutions/PSTeachingTools/blob/master/docs/about_PSTeachingTools.md)help file for more information.
Typed Demos

The module also includes a function for simulating an interactive PowerShell console session. You can type your commands in a file and have the function "play back" the commands just as if you were typing the commands. The function will pause after every | character. Pressing Enter will advance the demo. Read help for [Start-TypedDemo](https://github.com/jdhitsolutions/PSTeachingTools/blob/master/docs/Start-TypedDemo.md).

**Comment by jdhitsolutions** [comment]
Fixed the links in `README.md`. It was a case-sensitive issue with the Docs folder name.
